alias: Afvalmelding
description: Melding dag voor afval
trigger:
  - platform: time
    at: '18:00'  # de tijd dat het bericht gestuurd wordt
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.afvalinfo_thuis_tomorrow  #Let goed op of de naam van deze sensor klopt, met name het 3e gedeelte!
        state: none
action:
  - service: notify.notify
    data:
      message: 'Afval morgen: {{states.sensor.afvalinfo_thuis_tomorrow.state}}'  #Let goed op of de naam van deze sensor klopt, met name het 3e gedeelte!
      title: Afval morgen
mode: single
