alias: Afvalmelding
description: Melding dag voor afval
trigger:
  - platform: time
    at: '18:00'  # de tijd dat het bericht gestuurd wordt
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.afvalinfo_afval_voor_morgen
        state: none
action:
  - service: notify.notify
    data:
      message: 'Afval morgen: {{states.sensor.afvalinfo_afval_voor_morgen.state}}'  
      title: Afval morgen
mode: single
