sensor: # Als je al een sensor blok hebt in je configuratie dan deze regel NIET kopieren

# Afvalinfo
  - platform: afvalinfo       # naam van de integratie, in dit geval dus afvalinfo
    resources:                # De sensors voor alle afvalsoorten die jouw gemeente ondersteund. Verwijder de afvalsoorten die je gemeente niet heeft en/of die je niet weer wilt geven in HA
      - gft
      - kerstboom
      - pbd
      - papier
      - takken                # Ophalen van takken wordt ondersteund door ongeveer 50% van de gemeenten
      - restafval
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: drimmelen       # De naam van jouw gemeente
    postcode: 1234AA          # Jouw postcode format: 1234AA
    streetnumber: 24          # Jouw huisnummer zonder toevoegingen
    streetnumbersuffix: ""    # Eventuele toevoegingen
    dateformat: "%a %d %b %Y" # Weergaveformaat van de datums. In dit geval: Wo 24 Dec 2021
    locale: "nl"              # De taal waarin afvalinfo zijn tekst in moet weergeven
